site_name: BYOD Wiki
repo_url: https://github.com/UvA-FNWI/byod-wiki/
repo_name: BYOD Wiki
edit_uri: edit/main/docs/
markdown_extensions:
  - footnotes
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - search
  - git-revision-date-localized:
      type: datetime
theme:
  name: material
  logo: assets/uva.png
  favicon: assets/uva.png
  language: nl
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs # Show top level sections as tabs in navbar
    - navigation.sections # Show second level sections in bold, without requiring a click to expand
    - navigation.indexes # Do not show index pages separately
  palette:
    - scheme: default
      primary: red # TODO Use UvA red color https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-colors
      toggle:
        icon: material/weather-sunny
        name: Donker thema
    - scheme: slate
      primary: grey
      toggle:
        icon: material/weather-night
        name: Licht thema
