site_name: BYOD Wiki
repo_url: https://github.com/UvA-FNWI/byod-wiki/
repo_name: BYOD Wiki
edit_uri: edit/main/docs/
markdown_extensions:
  - footnotes
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
theme:
  name: material
  logo: assets/uva.png
  favicon: assets/uva.png
