site_name: BYOD Wiki
repo_url: https://github.com/UvA-FNWI/byod-wiki/
repo_name: BYOD Wiki
edit_uri: edit/main/docs/
markdown_extensions:
  - footnotes
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
theme:
  name: material
  logo: assets/uva.png
  favicon: assets/uva.png
  palette:
    - scheme: default
      primary: red # TODO Use UvA red color https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-colors
      toggle:
        icon: material/weather-sunny
        name: Donker thema
    - scheme: slate
      primary: grey
      toggle:
        icon: material/weather-night
        name: Licht thema
