site_name: BYOD Wiki
repo_url: https://github.com/UvA-FNWI/byod-wiki/
repo_name: BYOD Wiki
edit_uri: edit/main/docs/
markdown_extensions:
  - footnotes
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - search
  - git-revision-date-localized:
      type: datetime
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  logo: assets/uva.png
  favicon: assets/uva.png
  language: nl
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs # Show top level sections as tabs in navbar
    - navigation.sections # Show second level sections in bold, without requiring a click to expand
    - navigation.indexes # Do not show index pages separately

  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Donker thema
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Licht thema

# Manual navigation to change ordering and use correct capitalization in words like macOS
nav:
  - 'Hoofdpagina': 'index.md'
  - 'Software':
    - 'Software': 'software/index.md'
    - 'Git': 'software/git.md'
    - 'Python': 'software/python.md'
    - 'LaTeX': 'software/latex.md'
    - 'Matlab': 'software/matlab.md'
  - 'Linux':
    - 'Linux': 'linux/index.md'
    - 'Eduroam': 'linux/eduroam.md'
    - 'UvA VPN': 'linux/vpn.md'
    - 'Backups': 'linux/backups.md'
    - 'Installatie':
      - 'Installatie': 'linux/installatie/index.md'
      - 'Shell Script': 'linux/installatie/shell-script.md'
      - 'BitLocker': 'linux/installatie/bitlocker.md'
      - 'Veelvoorkomende Problemen': 'linux/installatie/problemen.md'
  - 'macOS':
    - 'macOS': 'mac-os/index.md'
    - 'Eduroam': 'mac-os/eduroam.md'
    - 'Uva VPN': 'mac-os/vpn.md'
    - 'Installatie': 'mac-os/installatie.md'
  - 'Vakinformatie':
    - 'Vakinformatie': 'vakinfo/index.md'
    - 'Informatica':
      - 'Jaar 1':
        - 'Inleiding Programmeren': 'vakinfo/inf/1/inpr.md'
        - 'Architectuur en Computerorganisatie': 'vakinfo/inf/1/arco.md'
        - 'Datastructuren en Algoritmen': 'vakinfo/inf/1/davi.md'
        - 'Discrete Wiskunde en Logica': 'vakinfo/inf/1/diwl.md'
        - 'Webprogrammeren en Databases': 'vakinfo/inf/1/wdvi.md'
        - 'Lineaire Algebra': 'vakinfo/inf/1/lial.md'
        - 'Programmeertalen': 'vakinfo/inf/1/prog.md'
        - 'Automaten en Formele Talen': 'vakinfo/inf/1/auft.md'
        - 'Besturingssystemen': 'vakinfo/inf/1/best.md'
        - 'Multimedia': 'vakinfo/inf/1/mult.md'
      - 'Jaar 2':
        - 'Moderne Databases': 'vakinfo/inf/2/mdvi.md'
        - 'Networks and Network Security': 'vakinfo/inf/2/nens.md'
        - 'Algoritmen en Complexiteit': 'vakinfo/inf/2/alco.md'
        - 'Distributed and Parallel Programming': 'vakinfo/inf/2/copp.md'
        - 'Numerical Recipes Project': 'vakinfo/inf/2/nurp.md'
        - 'Introduction Computational Science': 'vakinfo/inf/2/incs.md'
        - 'Statistisch Redeneren': 'vakinfo/inf/2/stre.md'
        - 'Reflectie op de Digitale Samenleving': 'vakinfo/inf/2/rods.md'
        - 'Introduction to Computer Vision': 'vakinfo/inf/2/itcv.md'
        - 'Project Software Engineering': 'vakinfo/inf/2/prse.md'
